# Configuration file
---
dataset_directory: /home/silo1/mas322/amex-default-prediction/
checkpoint_directory: /home/silo1/mas322/model-checkpoints/
experiment_directory: /home/silo1/mas322/experiment-results-2/
dain_repo: /home/mas322/dain/
mlproject_repo: /home/mas322/mlproject/
train_splits: 10
test_splits: 20
# End config
...
